spring.application.name=ecommerce
server.port=9090

# Configuración de la Base de Datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Muestra las consultas SQL reales en la consola y actualiza las tablas automáticamente
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Habilita la consola web de H2 para verificar las tablas si lo deseas
spring.h2.console.enabled=true